// Generated by CoffeeScript 1.6.2
ig.module('game.entities.hud').requires('impact.entity').defines(function() {
  var PADDING;

  PADDING = 20;
  return window.EntityHud = ig.Entity.extend({
    font: new ig.Font("media/fonts/existence_light_16.png"),
    init: function(settings) {
      this.parent(settings);
      this.settings = settings;
      this.initWidthHeight();
      this.player = this.settings.player;
      this.score_text = "";
      return this.lives_text = "";
    },
    update: function() {
      this.parent();
      this.score_text = "Score: " + this.player.score;
      return this.lives_text = "Lives: " + this.player.lives;
    },
    draw: function() {
      this.font.draw(this.score_text, PADDING, PADDING);
      return this.font.draw(this.lives_text, ig.system.width - PADDING, PADDING, ig.Font.ALIGN.RIGHT);
    },
    addAnims: function() {
      var anim, color, colors, frame, _i, _len, _results;

      colors = ['red', 'green', 'blue', 'yellow', 'white'];
      _results = [];
      for (frame = _i = 0, _len = colors.length; _i < _len; frame = ++_i) {
        color = colors[frame];
        anim = this.addAnim(color, 99, [0]);
        _results.push(anim.color = color);
      }
      return _results;
    },
    getAnimSheetForColor: function(color) {
      return new ig.AnimationSheet('media/white_320x240.png#' + this.hexForColor(color), this.width, this.height);
    },
    initWidthHeight: function() {
      this.height = this.font.height + PADDING;
      this.width = ig.system.width;
      this.size = {
        x: this.width,
        y: this.height
      };
      this.pos.x = 0;
      return this.pos.y = 0;
    }
  });
});
