// Generated by CoffeeScript 1.6.2
ig.module("game.main").requires("impact.game", "impact.font", "plugins.scene_manager", "game.menu_scene", "game.play_scene", "game.over_scene").defines(function() {
  var ParentGame;

  ParentGame = ig.Game.extend({
    sceneManager: new SceneManager(),
    main_music_track: new ig.Sound('media/music/theme.ogg', false),
    init: function() {
      ig.soundManager.volume = 0.1;
      this.menu_scene = new MenuScene(this);
      this.over_scene = new OverScene(this);
      this.sceneManager.replaceScene(this.menu_scene);
      if (typeof NO_MUSIC === "undefined" || NO_MUSIC === null) {
        return this.initMusic();
      }
    },
    update: function() {
      return this.sceneManager.updateScene();
    },
    draw: function() {
      return this.sceneManager.drawScene();
    },
    startGame: function() {
      this.play_scene = new PlayScene(this);
      this.play_scene.reset();
      this.sceneManager.replaceScene(this.play_scene);
      return ig.music.play();
    },
    endGame: function(args) {
      this.over_scene.setScore(args.score);
      this.sceneManager.replaceScene(this.over_scene);
      return ig.music.stop();
    },
    initMusic: function() {
      ig.music.add(this.main_music_track);
      return ig.music.volume = 0.5;
    }
  });
  return ig.main("#canvas", ParentGame, 60, 640, 480, 1);
});
