// Generated by CoffeeScript 1.6.2
ig.module("game.menu_scene").requires("impact.game", "impact.font", "plugins.scene_manager").defines(function() {
  return window.MenuScene = Scene.extend({
    title_font: new ig.Font("media/fonts/squared_48.png"),
    font: new ig.Font("media/fonts/squared_16.png"),
    init: function(manager) {
      this.manager = manager;
      return this.bindKeys();
    },
    bindKeys: function() {
      return ig.input.bind(ig.KEY.ENTER, 'start');
    },
    update: function() {
      this.parent();
      if (ig.input.pressed('start')) {
        return this.manager.startGame();
      }
    },
    draw: function() {
      var center_x, center_y, intro_text, text, top_y;

      this.parent();
      center_x = ig.system.width / 2;
      center_y = ig.system.height / 2;
      top_y = 40;
      text = "AVOLLECT\n";
      this.title_font.draw(text, center_x, center_y - 50, ig.Font.ALIGN.CENTER);
      intro_text = "Tap to start...\n\n";
      return this.font.draw(intro_text, center_x, center_y, ig.Font.ALIGN.CENTER);
    }
  });
});
